// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxlplbhrfeylnorekhoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4bHBsYmhyZmV5bG5vcmVraG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDI2MDEsImV4cCI6MjA2MTk3ODYwMX0.Vmmj3gzQr4308kZpJDOKrrKKqfdU1VneLKdtdVb_0Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);